audio:
  channels: 1
  chunk_size: 1024
  input_device: 4
  min_audio_length: 0.5
  sample_rate: 16000
  silence_duration: 1.5
  silence_threshold: 300
  vad_aggressiveness: 1
  vad_padding_ms: 300
commands:
  custom:
    address:
      action: '123 Main Street

        City, State 12345

        United States'
      category: dictation
      description: Insert home address
      patterns:
      - insert my address
      - type my address
      - home address
      type: type
    code_comment:
      action: '# TODO: Implement this functionality

        # Author: Your Name

        # Date: '
      category: dictation
      description: Insert code comment template
      patterns:
      - todo comment
      - insert todo
      - add todo
      type: type
    email_signature:
      action: 'Best regards,

        Your Name

        Email: your.email@example.com

        Phone: (555) 123-4567'
      category: dictation
      description: Insert email signature
      patterns:
      - insert signature
      - add my signature
      - email signature
      type: type
    lorem_ipsum:
      action: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation.
      category: dictation
      description: Insert Lorem Ipsum placeholder text
      patterns:
      - lorem ipsum
      - placeholder text
      - dummy text
      type: type
    meeting_intro:
      action: Good morning everyone, thank you for joining today's meeting. Let's
        begin by reviewing our agenda items.
      category: dictation
      description: Insert meeting introduction text
      patterns:
      - meeting introduction
      - intro text
      - meeting opener
      type: type
  start_dictation:
  - start dictation
  - begin dictation
  stop_dictation:
  - stop dictation
  - end dictation
  wake_words:
  - activate
  - computer
  - hey assistant
whisper:
  beam_size: 5
  best_of: 5
  compute_type: float16
  device: cuda
  engine: faster-whisper
  language: en
  model_size: large-v3
